interface FileSystemItem {
  name: string;
  type: "folder" | "file";
  description?: string;
  tables?: string[];
  referencedBy?: string[];
  erd?: string;
  children?: FileSystemItem[];
}
const fileSystem: FileSystemItem[] = [
  {
    name: "FHIR_Resources",
    type: "folder",
    children: [
      {
        erd: "/Account.png",
        name: "Account",
        type: "file",
        description:
          "The Account resource acts as a central record against which charges, payments, and adjustments are applied. It contains information about which parties are responsible for payment of the account.",
        tables: [
          "hc_account",
          "hc_account_guarantor",
          "hc_account_coverage",
          "hc_codeableconcept",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
          "hc_address",
          "hc_humanname",
          "hc_identifier",
          "hc_contactpoint",
        ],
        referencedBy: ["Encounter", "Episode of Care"],
      },
      {
        erd: "/AllergyIntolerance-2.png",
        name: "AllergyIntolerance",
        type: "file",
        tables: [
          "hc_allergyintolerance",
          "hc_allergyintolerance_category",
          "hc_allergyintolerance_reaction",
          "hc_codeableconcept",
          "hc_identifier",
          "hc_annotation",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
          "hc_contactpoint",
          "hc_address",
          "hc_humanname",
        ],
        description:
          "A record of a clinical assessment of an allergy or intolerance; a propensity, or a potential risk to an individual, to have an adverse reaction on future exposure to the specified substance, or class of substance. Where a propensity is identified, to record information or evidence about a reaction event that is characterized by any harmful or undesirable physiological response that is specific to the individual and triggered by exposure of an individual to the identified substance or class of substance. Substances include, but are not limited to: a therapeutic substance administered correctly at an appropriate dosage for the individual; food; material derived from plants or animals; or venom from insect stings",
      },
      {
        erd: "/ClaimResponse.png",
        name: "ClaimResponse",
        type: "file",
        tables: [
          "hc_claimresponse",
          "hc_claimresponse_additem",
          "hc_claimresponse_adjudication",
          "hc_claimresponse_detail",
          "hc_claimresponse_error",
          "hc_claimresponse_insurance",
          "hc_claimresponse_item",
          "hc_claimresponse_payment",
          "hc_claimresponse_processnote",
          "hc_claimresponse_subdetail",
          "hc_claimresponse_total",
          "hc_attachment",
          "hc_contactpoint",
          "hc_address",
          "hc_humanname",
          "hc_identifier",
          "hc_codeableconcept",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
        ],
        referencedBy: [
          "Claim",
          "ClaimResponse",
          "ExplanationOfBenefit",
          "MedicationRequest",
        ],
        description:
          "The ClaimResponse resource provides application level adjudication results, or an application level error, which are the result of processing a submitted Claim resource where that Claim may be the functional corollary of a Claim, Predetermination or a Preauthorization.This resource is the only appropriate response to a Claim which a processing system recognizes as a Claim resource. This is the adjudicated response to a Claim, Predetermination or Preauthorization. The strength of the payment aspect of the response is matching to the strength of the original request. For a Claim the adjudication indicates payment which is intended to be made. For Preauthorization no payment will actually be made however funds may be reserved to settle a claim submitted later. For Predetermination no payment will actually be made and no assurance is given that the adjudication of a claim submitted later will match the adjudication provided, for example funds may have been exhausted in the interim. Only an actual claim may be expected to result in actual payment.",
      },
      {
        name: "Condition",
        type: "file",
        description: "This is the description for the Condition resource.",
        tables: [
          "hc_condition",
          "hc_identifier",
          "hc_codeableconcept",
          "hc_reference",
          "hc_contactpoint",
          "hc_address",
          "hc_humanname",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_annotation",
          "hc_assigner",
        ],
      },
      {
        name: "Coverage",
        type: "file",
        description:
          "Financial instrument which may be used to reimburse or pay for health care products and services. Includes both insurance and self-payment.  The Coverage resource is intended to provide the high-level identifiers and descriptors of an insurance plan, typically the information which would appear on an insurance card, which may be used to pay, in part or in whole, for the provision of health care products and services.  Referenced By  Account, Claim, ClaimResponse, DeviceRequest, ExplanationOfBenefit.  https://hl7.org/fhir/r4/coverage.html",
        tables: [
          "hc_coverage",
          "hc_coverage_class",
          "hc_coverage_costtobeneficiary",
          "hc_coverage_exception",
          "hc_codeableconcept",
          "hc_identifier",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
          "hc_humanname",
          "hc_address",
          "hc_contactpoint",
        ],
      },
      {
        name: "Device",
        type: "file",
        description:
          "A type of a manufactured item that is used in the provision of healthcare without being substantially changed through that activity. The device may be a medical or non-medical device.  Referenced By  Account, Claim, ExplanationOfBenefit, Observation, Procedure  https://hl7.org/fhir/r4/device.html",
        tables: [
          "hc_device",
          "hc_device_specialization",
          "hc_device_devicename",
          "hc_device_udicarrier",
          "hc_device_property",
          "hc_device_version",
          "hc_annotation",
          "hc_identifier",
          "hc_codeableconcept",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
          "hc_contactpoint",
          "hc_address",
          "hc_humanname",
        ],
      },
      {
        name: "Encounter",
        type: "file",
        description:
          "Encounter resource represents an interaction between a patient and healthcare provider(s) for the purpose of providing healthcare services or assessing the patient's health status. It includes details such as the type, status, and period of the encounter, as well as the location and participants involved. This resource is essential for recording information about the context of care delivery, including inpatient, outpatient, and emergency visits. It helps in managing and exchanging data about patient visits, ensuring coordinated and comprehensive care.  Referenced By  Claim, ExplanationOfBenefit, Observation, Procedure   https://hl7.org/fhir/r4/encounter.html",
        tables: [
          "hc_encounter",
          "hc_encounter_classhistory",
          "hc_encounter_statushistory",
          "hc_encounter_location",
          "hc_encounter_participant",
          "hc_encounter_diagnosis",
          "hc_codeableconcept",
          "hc_identifier",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
          "hc_contactpoint",
          "hc_address",
          "hc_humanname",
        ],
      },
      {
        name: "EpisodeOfCare",
        type: "file",
        description:
          "EpisodeOfCare resource represents a span of healthcare service provided to a patient, often over a period of time, and typically covering a specific condition or healthcare issue. It includes details such as the managing organization, status, type, diagnosis, and the patient's care team. This resource helps in organizing and tracking the various care activities and encounters related to a particular medical condition or series of treatments. It is used to coordinate care across multiple services and providers, ensuring continuity and comprehensive management of the patient's health issues.  Referenced By  Encounter  https://hl7.org/fhir/r4/episodeofcare.html",
        tables: [
          "hc_episodeofcare",
          "hc_episodeofcare_diagnosis",
          "hc_episodeofcare_statushistory",
          "hc_identifier",
          "hc_codeableconcept",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
          "hc_contactpoint",
          "hc_address",
          "hc_humanname",
        ],
      },
      {
        name: "Location",
        type: "file",
        description:
          "Location resource represents a physical place where healthcare services are provided, such as a hospital, clinic, or ward. It includes details like the name, description, type, physical address, managing organization, and operational status of the location. This resource is crucial for identifying and managing the places where healthcare interactions occur, ensuring accurate and efficient coordination of services. It also supports the administrative and logistical aspects of healthcare delivery by providing information necessary for locating and utilizing healthcare facilities.  Referenced By  Account,Claim,ClaimResponse,Device,Encounter,ExplanationOfBenefit,Observation,PractitionerRole,Procedure,Provenance  https://hl7.org/fhir/r4/location.html",
        tables: [
          "hc_location",
          "hc_location_hoursofoperation",
          "hc_address",
          "hc_contactpoint",
          "hc_codeableconcept",
          "hc_identifier",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
          "hc_humanname",
        ],
      },
      {
        name: "MessageHeader",
        type: "file",
        description:
          "MessageHeader resource provides metadata about a message exchange, serving as a wrapper for communication between healthcare systems. It includes details such as the event type, source and destination of the message, timestamp, and any relevant identifiers. This resource is essential for tracking and managing the flow of information, ensuring messages are correctly routed and processed. By encapsulating the context and routing information, MessageHeader facilitates reliable and organized exchange of clinical and administrative data across different healthcare systems.  Referenced By  None  https://hl7.org/fhir/r4/messageheader.html",
        tables: [
          "hc_messageheader",
          "hc_messageheader_destination",
          "hc_contactpoint",
          "hc_codeableconcept",
          "hc_identifier",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
          "hc_address",
          "hc_humanname",
        ],
      },
      {
        name: "Observation",
        type: "file",
        description:
          "The FHIR Observation resource records measurements and clinical assessments related to a patient's health status, such as vital signs, laboratory results, and other clinical observations. It includes details like the observation's type, value, status, and the time it was made, as well as the subject (patient), performer (clinician), and any relevant interpretations or references. This resource is fundamental for capturing clinical data that informs diagnosis, treatment, and monitoring of health conditions. It supports interoperability by standardizing the way observations are documented and shared, ensuring consistency and accuracy in patient care.  Referenced By  Condition, Encounter, Procedure  https://hl7.org/fhir/r4/observation.html",
        tables: [
          "hc_observation",
          "hc_observation_referencerange",
          "hc_observation_component",
          "hc_identifier",
          "hc_codeableconcept",
          "hc_reference",
          "hc_annotation",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
          "hc_humanname",
          "hc_address",
          "hc_contactpoint",
        ],
      },
      {
        name: "Organization",
        type: "file",
        description:
          "Organization resource represents an entity involved in the provision or administration of healthcare services, such as hospitals, clinics, insurance companies, and governmental bodies. It includes details like the organization's name, type, contact information, address, and identifiers. This resource is crucial for managing and referencing the various institutions and groups within the healthcare system, ensuring clear communication and coordination. By standardizing information about organizations, it supports efficient administration, interoperability, and the accurate routing of healthcare data and services.  Referenced By  Account,Claim,ClaimResponse,Coverage,Device,Encounter,ExplanationOfBenefit,Location,MessageHeader,Observation,Patient,Practitioner,PractitionerRole,Procedure,Provenance  https://hl7.org/fhir/r4/organization.html",
        tables: [
          "hc_organization",
          "hc_organization_contact",
          "hc_identifier",
          "hc_codeableconcept",
          "hc_reference",
          "hc_contactpoint",
          "hc_address",
          "hc_humanname",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
        ],
      },
      {
        name: "Patient",
        type: "file",
        description:
          "Patient resource represents an individual receiving healthcare services. It includes details such as the patient's name, gender, birth date, contact information, and identifiers like medical record numbers. This resource is essential for documenting personal and demographic information critical to patient care, ensuring accurate identification and communication across healthcare systems. It supports interoperability by providing a standardized way to manage patient data, facilitating coordinated and continuous care.  Referenced By  Account,AllergyIntolerance,Claim,ClaimResponse,Condition,Coverage,Device,Encounter,ExplanationOfBenefit,Observation,Procedure,Provenance.  https://hl7.org/fhir/r4/patient.html",
        tables: [
          "hc_patient",
          "hc_patient_communication",
          "hc_patient_contact",
          "hc_patient_link",
          "hc_Identifier",
          "hc_codeableconcept",
          "hc_reference",
          "hc_contactpoint",
          "hc_address",
          "hc_humanname",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_attachment",
          "hc_assigner",
        ],
      },
      {
        name: "Practitioner",
        type: "file",
        description:
          "Practitioner resource represents an individual who is involved in the provision of healthcare services, such as a doctor, nurse, or therapist. It includes details like the practitioner's name, qualifications, contact information, and identifiers. This resource is vital for recording information about healthcare providers, ensuring accurate identification and credential verification. By standardizing practitioner data, it supports interoperability and effective coordination of care across different healthcare settings.  Referenced By  Account,AllergyIntolerance,Claim,ClaimResponse,Condition,Encounter,ExplanationOfBenefit,MessageHeader,Observation,Patient,PractitionerRole,Procedure,Provenance.  https://hl7.org/fhir/r4/practitioner.html",
        tables: [
          "hc_practitioner",
          "hc_practitioner_qualification",
          "hc_identifier",
          "hc_codeableconcept",
          "hc_reference",
          "hc_humanname",
          "hc_address",
          "hc_contactpoint",
          "hc_attachment",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
        ],
      },
      {
        name: "PractitionerRole",
        type: "file",
        description:
          "PractitionerRole resource specifies the roles and responsibilities of a practitioner within an organization. It includes details such as the practitioner, their role, the organization they work for, and the services they provide. This resource helps in managing the various functions and duties practitioners perform, facilitating appropriate assignment and coordination of tasks. It supports interoperability by clearly defining practitioner roles, ensuring accurate and efficient healthcare delivery.  Referenced By  Account,AllergyIntolerance,Claim,ClaimResponse,Condition,Encounter,ExplanationOfBenefit,MessageHeader,Observation,Patient,Procedure,Provenance  https://hl7.org/fhir/r4/practitionerrole.html",
        tables: [
          "hc_practitionerrole",
          "hc_practitionerrole_availabletime",
          "hc_practitionerrole_notavailable",
          "hc_codeableconcept",
          "hc_reference",
          "hc_contactpoint",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
          "hc_address",
          "hc_humanname",
          "hc_identifier",
        ],
      },
      {
        name: "Procedure",
        type: "file",
        description:
          "FHIR Procedure resource records actions taken to improve or assess a patient's health, such as surgeries, diagnostic tests, or therapies. It includes details like the type of procedure, date, status, performer, and patient. This resource is crucial for documenting medical interventions, providing a comprehensive view of the patient's treatment history. By standardizing procedure information, it supports accurate reporting, analysis, and coordination of care.  Referenced By  Claim,Encounter,ExplanationOfBenefit,Observation  https://hl7.org/fhir/r4/procedure.html",
        tables: [
          "hc_procedure",
          "hc_codeableconcept",
          "hc_identifier",
          "hc_reference",
          "hc_annotation",
          "hc_uri",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_assigner",
          "hc_contactpoint",
          "hc_address",
          "hc_humanname",
        ],
      },
      {
        name: "Provenance",
        type: "file",
        description:
          "The FHIR Provenance resource provides a record of the history and origin of a healthcare record or resource, documenting the changes and the actors involved in its creation or modification. It includes details such as the source of the resource, the agents responsible, the time of actions, and the reason for changes. This resource is essential for ensuring data integrity and accountability by tracking the lineage and authenticity of healthcare information. It supports auditing and compliance by providing a transparent history of how and by whom a resource was handled.  Referenced By  None  https://hl7.org/fhir/r4/provenance.html",
        tables: [
          "hc_provenance",
          "hc_provenance_agent",
          "hc_provenance_entity",
          "hc_provenance_signature",
          "hc_codeableconcept",
          "hc_identifier",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
          "hc_address",
          "hc_humanname",
          "hc_contactpoint",
        ],
      },
      {
        name: "RelatedPerson",
        type: "file",
        description: `RelatedPerson resource represents an individual who is involved in the care of a patient but is not a direct healthcare provider, such as a family member or caregiver. It includes details like their relationship to the patient, contact information, and identifiers. This resource is crucial for documenting the support network around a patient, facilitating communication and coordination of care. By capturing information about individuals who play a role in the patient's care, it helps ensure comprehensive and patient-centered care planning.
https://hl7.org/fhir/r4/relatedperson.html`,
        tables: [
          "hc_relatedperson",
          "hc_relatedperson_communication",
          "hc_address",
          "hc_contactpoint",
          "hc_codeableconcept",
          "hc_identifier",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_attachment",
          "hc_humanname",
          "hc_assigner",
        ],
        referencedBy: [
          `Account,AllergyIntolerance,Claim,Condition,Coverage,Encounter,ExplanationOfBenefit,Observation,Patient,Procedure,Provenance`,
        ],
      },
      {
        name: "ServiceRequest",
        type: "file",
        description: `
ServiceRequest resource documents a request for a healthcare service to be performed, such as diagnostic tests, treatments, or consultations. It includes details such as the requested service, requester, performer, priority, and patient. This resource is essential for managing and tracking the delivery of healthcare services, ensuring that appropriate actions are taken in response to clinical needs. By standardizing service requests, it supports efficient communication, coordination, and fulfillment of healthcare services across different providers and settings.
`,
        tables: [
          "hc_servicerequest",
          "hc_annotation",
          "hc_contactpoint",
          "hc_address",
          "hc_humanname",
          "hc_identifier",
          "hc_codeableconcept",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
        ],
        referencedBy: [
          `Claim,Encounter,ExplanationOfBenefit,Observation,Procedure
`,
        ],
      },
      {
        name: "ExplanationOfBenefit",
        type: "file",
        description:
          "ExplanationOfBenefit  ExplanationOfBenefit (EOB) resource provides a detailed accounting of the financial transactions related to the reimbursement of healthcare services. It includes information about the patient, provider, services rendered, and the amounts claimed, approved, and paid. This resource helps patients and providers understand the financial aspects of care, such as coverage details and patient responsibility. By standardizing financial information, it supports transparency, efficiency, and interoperability in healthcare billing and reimbursement.  Referenced By  None  https://hl7.org/fhir/r4/explanationofbenefit.html.",
        tables: [
          "hc_explanation_of_benefit",
          "hc_explanation_of_benefit_insurance",
          "hc_explanation_of_benefit_detail",
          "hc_explanation_of_benefit_item",
          "hc_adjudication",
          "hc_annotation",
          "hc_contactpoint",
          "hc_address",
          "hc_humanname",
          "hc_identifier",
          "hc_codeableconcept",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
        ],
      },
      {
        name: "Claim",
        type: "file",
        description:
          "Claim resource represents a request for payment for healthcare services provided to a patient, submitted by a healthcare provider to an insurer or payer. It includes details about the patient, services rendered, provider, and the claimed amount. This resource is essential for managing and processing healthcare billing, ensuring providers receive compensation for their services. By standardizing claim information, it facilitates accurate, efficient, and interoperable billing and reimbursement processes in healthcare.  Referenced By  ClaimResponse,ExplanationOfBenefit  https://hl7.org/fhir/r4/claim.html",
        tables: [
          "hc_claim",
          "hc_claim_procedure",
          "hc_claim_supportinginfo",
          "hc_claim_careteam",
          "hc_claim_diagnosis",
          "hc_claim_item",
          "hc_claim_insurance",
          "hc_claim_related",
          "hc_claim_accident",
          "hc_claim_payee",
          "hc_annotation",
          "hc_contactpoint",
          "hc_address",
          "hc_humanname",
          "hc_identifier",
          "hc_codeableconcept",
          "hc_reference",
          "hc_ancestor",
          "hc_extension",
          "hc_canonical",
          "hc_uri",
          "hc_assigner",
        ],
      },
      // Add other FHIR resources as needed...
    ],
  },
];

export default fileSystem;
